{
    'name': 'Bizfinder',
    'summary': 'Swedish company prospecting and lead generation, built into Odoo CRM.',
    'author': 'UCS OneDo AB',
    'website': 'https://www.ucsonedo.se',
    'support': 'info@ucsonedo.se',
    'category': 'Sales/CRM',
    'version': '19.0.3.1.2',
    'depends': ['base', 'web', 'crm', 'utm'],
    'data': [
        'security/ir.model.access.csv',
        'data/bizfinder_region_data.xml',
        'data/bizfinder_community_data.xml',
        'data/bizfinder_industry_data.xml',
        'data/bizfinder_legal_form_data.xml',
        'data/bizfinder_magnitude_data.xml',
        'data/bizfinder_source_data.xml',
        'data/bizfinder_cron_data.xml',
        'views/bizfinder_confirm_views.xml',
        'views/bizfinder_settings_views.xml',
        'views/bizfinder_usage_views.xml',
        'views/bizfinder_preset_views.xml',
        'views/bizfinder_wizard_views.xml',
        'views/bizfinder_crm_lead_views.xml',
        'views/bizfinder_partner_views.xml',
        'views/bizfinder_event_views.xml',
        'views/bizfinder_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'bizfinder/static/src/js/bizfinder_search_form.js',
            'bizfinder/static/src/scss/bizfinder_search.scss',
        ],
        'web.assets_tests': [
            'bizfinder/static/tests/tours/bizfinder_search_tour.js',
        ],
    },
    'images': ['static/description/bizfinder_results.png'],
    'license': 'LGPL-3',
    'application': True,
    'installable': True,
}
