from . import (
    bizfinder_client,
    bizfinder_community,
    bizfinder_company_event,
    bizfinder_filter_mixin,
    bizfinder_industry,
    bizfinder_legal_form,
    bizfinder_magnitude,
    bizfinder_preset,
    bizfinder_region,
    crm_lead,
    res_company,
    res_config_settings,
    res_partner,
)
